spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fx_insight_ware_house?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
server:
  port: 8082
